export const wittyFacts = [
    "Building a permanent record of knowledge. Let the other guy find you some flashy cartoons.",
    "My rival is busy analyzing a YouTuber's intro music. I'm analyzing your actual syllabus.",
    "Crafting notes you can skim in 5 minutes, not a video you have to sit through for 15.",
    "Because real learning doesn't come with a 'like and subscribe' button.",
    "I provide a searchable, skimmable source of truth. My rival provides... buffering.",
    "Let's be honest, you'll forget a video. You can't forget what you've read.",
    "My rival gives you someone else's opinion. I give you the facts, unadulterated.",
    "Distilling pure knowledge, not just transcribing a vlogger's script.",
    "This is for deep work. The other guy's for background noise.",
    "My rival's 'research' is finding a guy with a ring light. Mine is your textbook.",
    "I'm building your brain. My rival is trying to entertain it.",
    "A video is a suggestion. A well-written note is an instruction.",
    "My output fits in your mind. My rival's requires headphones.",
    "I trust your intelligence to read. I don't need to spoon-feed you with visuals.",
    "My rival is a glorified TV guide. I am the library.",
    "Why settle for a summary when you can have the source code of knowledge?",
    "Building connections between concepts, not just providing links to videos.",
    "I'm creating a silent, focused study environment. My rival is... loud.",
    "Let's create something you can actually use *during* an open-book exam.",
    "My rival's content is gone in a flash. My notes are forever.",
    "You can't CTRL+F a feeling. But you can CTRL+F my notes for the exact formula you need.",
    "My rival promotes passive watching. I enable active learning.",
    "Let's build something that works even when the Wi-Fi is down.",
    "Some people need a teacher to hold their hand. My users prefer to think for themselves.",
    "One day, my rival will ask me to generate notes on why reading is more effective. The irony will be delicious."
];