// src/lib/loadingFacts.js
export const wittyFacts = [
    "Crafting your high-ROI study schedule...",
    "Consulting the procrastination oracle...",
    "Brewing the perfect cup of focus...",
    "Untangling your syllabus spaghetti...",
    "Aligning your chakras for A+ grades...",
    "Reminding you to drink water...",
    "Calculating the optimal nap-to-study ratio...",
    "Turning 'Kal Padhunga' into 'Aaj Padhunga'...",
    "Defeating the final boss of distraction...",
    "Polishing the apples for your teachers...",
    "Decoding your professor's hieroglyphic notes...",
    "Sneaking into Einstein's DMs for tips...",
    "Sharpening your digital pencils...",
    "Telling Newton about your gravity-defying GPA...",
    "Fetching chai and motivation...",
    "Just one more loading bar till you become toppper™...",
    "Making sure your GPA won't ghost you...",
    "Slapping some sense into your syllabus...",
    "Outsourcing your stress to the cloud...",
    "Applying emotional support duct tape to your timetable...",
    "Training an AI just to understand your professor's jokes...",
    "Clearing cobwebs off last semester's guilt...",
    "Turning caffeine into productivity...",
    "Whispering sweet nothings to your brain cells...",
    "Hiring a virtual professor who doesn't take attendance...",
    "Downloading your syllabus through osmosis...",
    "Assembling neurons for max efficiency...",
    "AI is panicking so you don't have to...",
    "Deleting all 'Kal se padhenge' backups...",
    "Teaching electrons to form better thoughts...",
    "Making your brain lag a little less...",
    "Googling how to become the next topper...",
    "Running on coffee, code, and blind optimism...",
    "Running GPT on chai instead of GPUs...",
    "Searching for shortcuts in parallel universes...",
    "Outsmarting YouTube recommendations for you...",
    "Studies show 82.7% of toppers blink less during exams...",
    "AI cracked JEE but still fears viva questions...",
    "Your syllabus was last seen vacationing in Bali...",
    "Researchers confirm: Reading PDFs increases your weight by 0.5g...",
    "Fun fact: One minute of planning saves you 5 hours of crying...",
    "If you stare long enough at your notes, they stare back...",
    "A cat once passed an exam by walking on the keyboard. True story*...",
    "*This AI is 74% sure it knows what it's doing...",
    "We asked ChatGPT to explain Quantum Physics. It cried.",
    "Breaking News: AI found a motivation molecule. Lost it immediately.",
    "Scientific name for study motivation: *Rareus Appearus*...",
    "Study hack: Keep textbook under pillow. Hope for miracle...",
    "This plan is 100% algorithmically guilt-tripped...",
    "AI just beat its own high score in overthinking...",
];