// src/lib/studyTips.js
export const studyTips = [
    "Use the Pomodoro Technique: 25 minutes of focused study, followed by a 5-minute break. It's a marathon, not a sprint!",
    "Explain a concept to a friend (or a rubber duck!). Teaching is the best way to solidify your own understanding.",
    "Don't just re-read your notes. Use active recall methods like flashcards or quizzes to test your memory.",
    "Get enough sleep. Your brain consolidates memories and learns while you rest.",
    "Stay hydrated. Dehydration can significantly impair your cognitive function and focus.",
    "Turn off notifications while studying. FOMO can wait, your future can't.",
    "Studying in short bursts throughout the week beats one mega cram session.",
    "Write things down by hand—your brain remembers better when you physically write it.",
    "Set a daily 'just 10 minutes' study timer. Momentum often follows intention.",
    "Use spaced repetition to remember stuff long-term. Your future self will thank you.",
    "Study in the same place to train your brain it's 'focus mode' time.",
    "Set goals for each session. 'I'll finish chapter 2' is better than 'I'll just study.'",
    "Don't aim for perfect notes—aim for understanding. Clarity > Aesthetic.",
    "Background music? Try lo-fi or instrumentals. Lyrics often hijack your focus.",
    "Keep a 'doubt list' to ask your teacher later. Don't let confusion slow you down.",
    "Celebrate small wins. Finished a tough topic? Treat yourself with a snack or 10-min scroll guilt-free.",
    "Comparison kills motivation. Focus on your pace—progress is progress, even if it's slow.",
    "Motivation fades. Discipline doesn't. Build study habits that show up even when you don't feel like it.",
];